addevent/urls.py
from django.conf.urls import url
from . import views

app_name = 'addevent'


urlpatterns = [
	url(r'^$',views.index,name='index'),
        url(r'^addevent/$',views.addevent,name='addevent'),
        url(r'^ledger/$',views.ledger,name='ledger'),
]

myroom/urls.py
from django.conf.urls import url , include 
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('addevent.urls')),
    url(r'^addevent/',include('addevent.urls')),
]

addevent/models.py
from __future__ import unicode_literals

from django.db import models #models is a package


# Create your models here.
class RoomEvent(models.Model):
	evnt_date=models.DateTimeField(auto_now=True)
	evnt_doer=models.CharField(max_length=255)
	evnt_product=models.CharField(max_length=255)
	evnt_amount=models.IntegerField(default=0)
	evnt_doer_added_amount=models.IntegerField(default=0)
	evnt_details=models.CharField(max_length=1023)

	def __str__(self):
		return str(self.evnt_date) + ' - ' + self.evnt_doer + ' - ' + self.evnt_product

addevent/forms.py
from django import forms
from .models import RoomEvent

class RoomEventForm(forms.ModelForm):
	class Meta:
		model = RoomEvent
		fields=['evnt_doer','evnt_product','evnt_amount','evnt_doer_added_amount','evnt_details']

addevent/views.py
from django.shortcuts import render,get_object_or_404
from .models import RoomEvent
from django.db.models import Sum
from .forms import RoomEventForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

# Create your views here.

def index(request):
	rec_rohith = RoomEvent.objects.filter(evnt_doer__contains='ohit').aggregate(Sum('evnt_doer_added_amount'))
	rec_jagadish = RoomEvent.objects.filter(evnt_doer__contains='agadish').aggregate(Sum('evnt_doer_added_amount'))
	rec_rishi = RoomEvent.objects.filter(evnt_doer__contains='ishi').aggregate(Sum('evnt_doer_added_amount'))
	rec_nikhil = RoomEvent.objects.filter(evnt_doer__contains='ikhil').aggregate(Sum('evnt_doer_added_amount'))
	rec_hemanth = RoomEvent.objects.filter(evnt_doer__contains='emant').aggregate(Sum('evnt_doer_added_amount'))
	rec_akshay = RoomEvent.objects.filter(evnt_doer__contains='ksha').aggregate(Sum('evnt_doer_added_amount'))
	rec_room = RoomEvent.objects.filter().aggregate(Sum('evnt_doer_added_amount'))
	rec_spent_room = RoomEvent.objects.filter().aggregate(Sum('evnt_amount'))
	context = {'rec_rohith':rec_rohith,'rec_jagadish':rec_jagadish,'rec_rishi':rec_rishi,'rec_nikhil':rec_nikhil,'rec_hemanth':rec_hemanth,'rec_akshay':rec_akshay,'rec_room':rec_room,'rec_spent_room':rec_spent_room,}
	return render(request, 'addevent/index.html',context)		 

def addevent(request):
	form = RoomEventForm(request.POST or None)
        if form.is_valid():
        	anevent = form.save(commit=False)
		anevent.save()
		return HttpResponseRedirect(reverse('addevent:ledger'))
	context= {"form":form,}
	return render(request,'addevent/addevent.html',context)

def ledger(request):
	allevents=RoomEvent.objects.all()
	context={'allevents':allevents,}
	return render(request,'addevent/ledger.html',context)

addevent/templates/addevent/addevent.html
{% extends 'addevent/base.html' %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add Purchase</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form"  method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
			 <div class="form-group">
       				 <div class="col-sm-offset-2 col-sm-10">
           			 <span class="text-danger small">{{ field.errors }}</span>
        			</div>
        			<label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        			<div class="col-sm-10">{{ field }}</div>
    			</div>
			{% endfor %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" id="redir" onclick="showmessage()"  class="btn btn-success">Submit</button>
				<script>
				function showmessage(){
				document.getElementById("msg").innerHTML=" * Transaction successful";
				//location.href = "{% url 'addevent:ledger' %}";
				}
				</script>
                            </div>
                        </div>
			<p color="green" id="msg" border=2px position="fixed"></p>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

addevent/templates/addevent/base.html
<!doctype html>
<html lang="en">
<head>
<title>{% block title %}Our Room{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse" style="border-radius:0">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'addevent:index' %}">Our Room</a>
        </div>
        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'addevent:addevent' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Purchase
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'addevent:ledger' %}">
                        <span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span>&nbsp; View Ledger
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

addevent/templates/addevent/index.html
{% extends 'addevent/base.html' %}
{% block body %}
<div class="albums-container container-fluid">

    <!-- Room Members -->
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <h3>Summary</h3>
        </div>
    </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Paid Amount</th>
                                <th>Phone</th>
                            </tr>
                        </thead>
                        <tbody>
                                <tr>
                                    <td><a href="https://www.facebook.com/rohithreddykota" text-decoration="none">Rohith Reddy Kota</a></td>
                                    <td>{{ rec_rohith.evnt_doer_added_amount__sum }}</td>
				    <td>+918527969790</td>
                                </tr>
                                <tr>
                                    <td><a href="https://www.facebook.com/rishyendra.kiran" text-decoration="none">Rishi Chowdary</a></td>
                                    <td>{{ rec_rishi.evnt_doer_added_amount__sum }}</td>
                                    <td>+918500058802</td>
                                </tr>
                                <tr>
                                    <td><a href="https://www.facebook.com/jagadish.krishna.7" text-decoration="none">Jagadish Krishna Chowdary</a></td>
                                    <td>{{ rec_jagadish.evnt_doer_added_amount__sum }}</td>
                                    <td>+918121275675</td>
                                </tr>
                                <tr>
                                    <td><a href="https://www.facebook.com/rhemanth.goud"  text-decoration="none">R Hemanth Goud</td>
                                    <td>{{ rec_hemanth.evnt_doer_added_amount__sum }}</td>
                                    <td>+919100091188</td>
                                </tr>
                                <tr>
                                    <td><a href="https://www.facebook.com/akshayreddy.chinnolla" text-decoration="none">Akshay Reddy</a></td>
                                    <td>{{ rec_akshay.evnt_doer_added_amount__sum }}</td>
                                    <td>+918464050504</td>
                                </tr>
                                <tr>
                                    <td><a href="#" text-decoration="none">Nikhil</td>
                                    <td>{{ rec_nikhil.evnt_doer_added_amount__sum }}</td>
                                    <td>+919494959984</td>
                                </tr>
                           <!-- <tr>
                                    <td><strong>Total Available Money</strong></td>
                                    <td>{{ rec_room.evnt_doer_added_amount__sum }}</td>
                                    <td>+918121275675</td>
                             --></tr>
                                <tr>
                                    <td><strong>Total Spent Money</strong></td>
                                    <td>{{ rec_spent_room.evnt_amount__sum }}</td>
                                    <td>+918121275675</td>
                                </tr>
                          </tbody>
                    </table>
                </div>
            </div>
            <h3 color="blue">What is for next version (Version 1.1)?</h3>
            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table table-striped">
                            <tr>
                                <td>1</td>
                                <td>Each user will be given a User ID and Password.</td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>A user can see only their record informantion.</td>
                            </tr>
                            <tr>
                                <td>3</td>
                                <td>After submitting "add purchase", you will be redirected to your ledger information page automatically.</td>
                            </tr>
                    <tbody>
                </div>
            </div>

    </div>
</dev>
{% endblock %}

addevent/templates/addevent/ledger.html
{% extends 'addevent/base.html' %}
{% block body %}
<div class="container-fluid ledger-container">
    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Name</th>
                                <th>Product</th>
                                <th>Puchase Amount</th>
				<th>Amount He Added</th>
                                <th>details</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for event in allevents %}
                                <tr>
                                    <td>{{ event.evnt_date }}</td>
                                    <td>{{  event.evnt_doer }}</td>
                                    <td>{{  event.evnt_product }}</td>
                                    <td>{{  event.evnt_amount }}</td>
                                    <td>{{  event.evnt_doer_added_amount }}</td>
				    <td>{{  event.evnt_details }}</td>
				</tr>
			    {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}